version: '3.9'
name: "requesto"

services:
    nginx:
        image: nginx
        restart: always
        container_name: simple_nginx
        environment:
            - VIRTUAL_HOST=site.local
        depends_on:
            - php
        networks:
            - backend
        volumes:
            - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
            - ../:/var/www/html/
        ports:
            - "80:80"
#    composer:
#        image: composer/composer:latest
#        volumes:
#            - ../client:/var/www/html/client
#        command: install --prefer-dist --no-interaction
    php:
        build:
            context: ..
            dockerfile: deploy/Dockerfile
        image: app
        container_name: app
        restart: always
        volumes:
            - ../client:/var/www/html/client
           # - .:/var/www/html
            - ../recursion:/var/www/html/recursion
            - ../index.php:/var/www/html/index.php
        entrypoint: sh /var/www/html/client/entrypoint.sh
        networks:
            - backend
        tty: true

#volumes:
#    client:
#        driver: local
#        driver_opts:
#            type: 'none'
#            o: 'bind'
#            device: '../client'

networks:
    backend:
    